# 🚀 Fly.io Configuration for Italian Meme Stock Exchange
# Deploy with: fly deploy

app = "italian-meme-exchange"
primary_region = "fra"  # Frankfurt - good for Europe/global

[build]
  dockerfile = "Dockerfile.fly"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  DASHBOARD_PORT = "8080"

# Main service (Discord Bot + Dashboard)
[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

# Health checks
[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false

# Persistent storage for data files
[mounts]
  source = "data_volume"
  destination = "/app/data"

# Auto-scaling
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # Keep Discord bot always running
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3

# Resources
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
