# 🚀 Railway Deployment Configuration
# Deploy to Railway with one click: https://railway.app

# Railway automatically detects Node.js projects
# This file ensures proper configuration

# Build command (Railway will run this)
# npm run build

# Start command (Railway will run this)
# npm run production

# Environment Variables to set in Railway Dashboard:
# - NODE_ENV=production
# - PORT=3000
# - DISCORD_TOKEN=your_discord_token
# - DISCORD_CLIENT_ID=your_client_id
# - SUPABASE_URL=your_supabase_url
# - SUPABASE_ANON_KEY=your_supabase_key
# - DASHBOARD_PORT=3002
# - API_PORT=3001

# Railway-specific settings
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: ${{RAILWAY_STATIC_URL}}
    healthcheck:
      url: /health
      interval: 30s
      timeout: 10s
      retries: 3
    
# Automatic deployments on git push
deploy:
  on:
    push:
      branches: [main, master]

# Custom start script for Railway
nixpacks:
  phases:
    setup:
      nixLibs:
        - nodejs_18
    build:
      cmds:
        - npm ci --only=production
    start:
      cmd: npm run production
